### ISSUE TITLE
Help for a beginner

### ISSUE THREAD

**Issue by ms3056** [podondra/gym-gridworlds#2]
Hi - I am hoping you can help get me started. I would like to use your environment to experiment with machine learning but I am having some trouble getting going. 

I have everything cloned and updated but I am unable to get env = gym.make('Gridworld-v0')  to open up an environment. I was wondering if you could possibly take the time to help me out and create a very simple python program starts the environment going visually so I can start to learn?

Thanks for any time you decide to spend on this for me.

**Comment by podondra** [comment]
Hi @ms3056 :blush: Sure but you have to provide more information.

**Comment by ms3056** [comment]
Hi, there - thank you so much for taking the time to respond. I have corrected my error. I am new to Python, and I had five different Python environments all over the place. I think my setup in Visual Studio Code was getting confused and not pointing to the right place. 

Thanks again for taking the time to respond.

**Comment by podondra** [comment]
You are welcome :blush: Have fun!
